apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-gateway
  labels:
    app: service-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-gateway
  template:
    metadata:
      labels:
        app: service-gateway
    spec:
      containers:
      - name: app-gateway
        image: stivid007/app-gateway:2
        ports:
        - containerPort: 8080
        env:
        - name: NACOS_SERVERADDR
          value: "164.90.255.230:8848"
        - name: NACOS_NAMESPACE
          value: "aforo255"
        - name: NACOS_IDENTITYKEY
          value: "nacos"
        - name: NACOS_IDENTITYVALUE
          value: "nacos"
        - name: NACOS_ENV
          value: "PROD"
---
kind: Service
apiVersion: v1
metadata:
  name: app-service-gateway
spec:
  type: LoadBalancer
  selector:
    app: service-gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http